version: '3.7'

services:
  todo-app:
    image: ritesh1999/node-todo:latest
    ports:
      - "8000:8000"
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:

     MYSQL_ROOT_PASSWORD: test@123
